name: Lint

on: [push]

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check by black
        uses: psf/black@stable
        with:
          options: "--check --diff -v"
  black:
    runs-on: ubuntu-latest
    needs: black-check
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format by black
        uses: psf/black@stable
        with:
          options: "-v"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format by black"
