name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format by black
        uses: psf/black@stable
        with:
          options: "--line-length 79"
