name: Lint

on: [push]

jobs:
  isort-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Check by isort
        uses: isort/isort-action@master
  isort:
    runs-on: ubuntu-latest
    needs: isort-check
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Format by isort
        uses: isort/isort-action@master
        with:
          configuration: "-v"
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format by isort"

  black-check:
    runs-on: ubuntu-latest
    needs: isort
    # not failure == (success or skipped)
    if: ${{ ! failure() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check by black
        uses: psf/black@stable
        with:
          options: "--check --diff -v"
  black:
    runs-on: ubuntu-latest
    needs: black-check
    if: failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format by black
        uses: psf/black@stable
        with:
          options: "-v"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format by black"
