name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install black isort
      - name: Git configuration
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
      - name: Sort imports if needed
        # actions/checkout@v2 を使っているので、コミット作成が以下のように書ける
        # ref: https://stackoverflow.com/a/58393457
        run: |
          isort --check-only --diff . || isort -v .
          git commit -am "[style] Format Python code with isort in GitHub Actions"
          git push
      - name: Format with black if needed
        run: |
          git pull
          black --check --diff . || black -v .
          git commit -am "[style] Format Python code with black in GitHub Actions"
          git push
